//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by cpw.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_ORDEN                       104
#define ID_BORRAR_MAQ                   104
#define IDD_INTR_LONG                   105
#define ID_INSERT_MAQ                   105
#define IDD_VALIDAR_CAMBIO              107
#define ID_LEFT_MAQ                     108
#define ID_RIGHT_MAQ                    109
#define ID_LISTAR_GRAF                  110
#define ID_CARGA_GFH                    112
#define ID_REPROG_GFH                   113
#define ID_CALEND_GFH                   114
#define IDR_TEXTTYPE                    117
#define ID_TIPO_LETRA_TXT               118
#define ID_DIVIDIR_ORDEN                119
#define ID_NUEVA_ORDEN                  120
#define IDR_MAINFRAME                   128
#define IDR_CPWTYPE                     129
#define IDD_ESCALA                      130
#define IDS_OF_NOTFOUND                 130
#define IDD_CARGAINICIAL                131
#define IDS_ERR_CANTEXC                 131
#define IDD_INTR_DBL                    132
#define IDS_CONF_ADDCANT                132
#define IDC_MOVE                        133
#define IDS_CONF_ADDMAQ                 133
#define IDS_ERR_NOMAQMOL                134
#define IDR_POPUP                       135
#define IDS_DLG_ARTICTXT                135
#define IDD_PRINT                       136
#define IDS_DLG_ARTICIT                 136
#define ID_CONSART_MAQ                  136
#define IDD_BUSCAR_ORDEN                137
#define IDW_VERBAR                      137
#define IDD_INTR_DATE                   138
#define ID_CERRAR_OFS                   138
#define IDD_INSERT_MAQ                  139
#define ID_ABRIR_OFS                    139
#define ID_UNIR_ORDEN                   140
#define IDB_BITMAP1                     141
#define ID_MY_ENTER                     141
#define IDC_CURSOR1                     142
#define ID_CAMBIAR_PERSONAS             142
#define IDD_OPCIONES                    143
#define IDD_DIALOG1                     144
#define IDD_DEBUG                       144
#define IDC_CURSOR2                     145
#define IDD_LST_MAQ                     145
#define IDD_INTR_STR                    146
#define IDR_DESPL_OF                    151
#define IDD_AJUSTAR                     153
#define IDD_LINEA                       154
#define IDD_CAMBIO_MOLDE                161
#define IDD_LISTA                       165
#define IDB_MOLDE_REP                   169
#define IDB_MOLDE_EA                    170
#define IDB_MOLDE_CF                    171
#define IDD_SELEC_EMPRESA               171
#define IDB_MOLDE_DP                    172
#define IDD_EXCEL                       172
#define IDB_BITMAP2                     173
#define IDB_MOLDE                       173
#define IDB_MOLDE_MK19                  174
#define TK_AA_INI_OF_VALUES             500
#define TK_ID_FECFIN                    501
#define TK_ID_FECINI                    502
#define TK_ID_LOTE                      503
#define TK_ID_MARGEN                    504
#define TK_ID_PESTOT                    505
#define TK_ID_PESUNI                    506
#define TK_ID_PORCHAT                   507
#define TK_ID_PORINAC                   508
#define TK_ID_CANTFAB                   509
#define TK_ID_CANTCHAT                  510
#define TK_ID_TOTHORAS                  511
#define TK_ID_CLIENTE                   512
#define TK_ID_MEZCLA                    513
#define TK_ID_HORMEZ                    514
#define TK_ID_NECMEZ                    515
#define TK_ZZ_END_OF_VALUES             550
#define TK_ZZ_END_RESERVED              600
#define IDC_ESCALA                      1001
#define IDC_EBLOQUE                     1001
#define IDC_SPIN_ESCALA                 1002
#define IDC_BLOQUE                      1003
#define IDC_INICIO                      1003
#define IDC_DESDE_ORDEN                 1004
#define IDC_TIEMPO                      1004
#define IDC_DBL_VALUE                   1004
#define IDC_HASTA_ORDEN                 1005
#define IDC_FINAL                       1005
#define IDC_BORRAR                      1006
#define IDC_INICIO_FIJO                 1007
#define IDC_FABRICADA                   1007
#define IDC_TIEMPO_FIJO                 1008
#define IDC_MAQUINAS                    1009
#define IDC_DESDE_FECHA                 1009
#define IDC_ORDFAB                      1010
#define IDC_TIEMPO_TOT                  1010
#define IDC_CANTIDAD                    1011
#define IDC_HASTA_FECHA                 1011
#define IDC_FECENT                      1012
#define IDC_TIPO_LISTADO                1012
#define IDC_DESDE_GFH                   1013
#define IDC_ACABADO                     1013
#define IDC_PERSONAS                    1014
#define IDC_HASTA_GFH                   1014
#define IDC_LONGITUD                    1015
#define IDC_DESDE_MAQ                   1015
#define IDC_HASTA_MAQ                   1016
#define IDC_CELULA                      1017
#define IDC_CELALT                      1018
#define IDC_CAPTION                     1018
#define IDC_LIMITADA                    1019
#define IDC_LONG_VALUE                  1019
#define IDC_CAMPO                       1020
#define IDC_VALOR_ANTIGUO               1021
#define IDC_VALOR_NUEVO                 1022
#define IDC_ORDEN                       1026
#define IDC_FECHA                       1035
#define IDC_INSMAQ_MAQ                  1037
#define IDC_INSMAQ_ANTES                1038
#define IDC_INSMAQ_DESPUES              1039
#define IDC_ANTES_DESPUES               1040
#define IDC_FECHA_FIJA                  1042
#define IDC_FECINI                      1044
#define IDC_FECFAB                      1046
#define IDC_FABRICADAS                  1047
#define IDC_RESTANTES                   1048
#define IDC_FECFIN                      1049
#define IDC_CADENCIA                    1051
#define IDC_INACTIVIDAD                 1052
#define IDC_SELECTED                    1053
#define IDC_TIRADAS                     1054
#define IDC_CS9                         1055
#define IDC_MASA                        1056
#define IDC_COLOR_0                     1056
#define IDC_COLOR_1                     1057
#define IDC_COLOR_2                     1058
#define IDC_PAR_HORDIFNESS              1059
#define IDC_COLOR_3                     1059
#define IDC_COLOR_4                     1060
#define IDC_MAQMOL                      1061
#define IDC_COLOR_5                     1061
#define IDC_LOTE                        1062
#define IDC_CHATARRAS                   1063
#define IDC_DEBUGLIST                   1064
#define IDC_LSC_MAQORD                  1066
#define IDC_FEC_DESDE                   1068
#define IDC_FEC_HASTA                   1069
#define IDC_MOLDE                       1071
#define IDC_AJUSTAR                     1073
#define IDC_FINALIZAR                   1074
#define IDC_PRINT_MAQORD                1075
#define IDC_STR_VALUE                   1076
#define IDC_INSMAQ                      1077
#define IDC_CANT_ACT                    1078
#define IDC_CANT_NUE                    1079
#define IDC_MATERIAL                    1080
#define IDC_EXISTENCIAS                 1082
#define IDC_RATIO                       1083
#define IDC_CAD_ANT                     1085
#define IDC_CAD_NUE                     1086
#define IDC_HORAS                       1087
#define IDC_SPIN_HORAS                  1088
#define IDC_SPIN_RATIO                  1089
#define IDC_SPIN_CAD                    1090
#define IDC_HORAS_D                     1091
#define IDC_RATIO_D                     1092
#define IDC_CAD_D                       1093
#define IDC_LIN_MAQ                     1094
#define IDC_LIN_ART                     1095
#define IDC_LIN_CANT                    1096
#define IDC_LIN_CAD                     1097
#define IDC_LIN_HORAS                   1098
#define IDC_LIN_MEZCLA                  1099
#define IDC_LIN_MOLDE                   1101
#define IDC_FEC_CAMBIO                  1103
#define IDC_MAQ_CAMBIO                  1104
#define IDC_MOLENT_CAMBIO               1105
#define IDC_MOLSAL_CAMBIO               1106
#define IDC_LISTA1                      1107
#define IDC_MEZCLA                      1109
#define IDC_MEZCLAKILOS                 1110
#define IDC_PESOGRAMOS                  1111
#define IDC_CAVIDADES                   1112
#define IDC_CONSUMO                     1113
#define IDC_RESTHORAS                   1114
#define IDC_RESTCANT                    1115
#define IDC_LISTA                       1116
#define IDC_BUT_NOPROG                  1117
#define IDC_AJUSTAR_A_MEZCLA            1118
#define IDC_CANT_TOT                    1119
#define IDC_MARGEN_MIN_2                1120
#define IDC_MARGEN_MIN_3                1121
#define IDC_MARGEN_MIN_4                1122
#define IDC_RICHEDIT1                   1125
#define IDC_RICHEDIT2                   1126
#define IDC_RICHEDIT3                   1127
#define IDC_MARGEN_MAX_3                1128
#define IDC_CADENCIA_ACABADO            1128
#define IDC_MARGEN_MAX_4                1129
#define IDC_EMPRESA                     1129
#define IDC_MARGEN_MAX_5                1130
#define IDC_RICHEDIT4                   1131
#define IDC_COMPONENTES                 1131
#define IDC_RICHEDIT5                   1132
#define IDC_MOLDE_DETALLE               1132
#define IDC_RICHEDIT6                   1133
#define ID_TEST                         32771
#define ID_ESCALA                       32772
#define ID_CARGAINICIAL                 32773
#define ID_EDITAR_ORDEN                 32774
#define ID_BUSCAR_ORDEN                 32775
#define ID_MOVER_ORDEN                  32776
#define ID_RECALCULAR                   32777
#define ID_LISTAR_MAQ                   32778
#define ID_EDITAR_CALEND                32779
#define ID_RECALC_MAQ                   32780
#define ID_CARGA_NESS                   32781
#define ID_CARGA_LLENADORAS             32782
#define ID_SELECT_END                   32783
#define ID_CARGA_ANTIGUO                32784
#define ID_REPROGRAMA_CELULAS           32785
#define ID_REPROGRAMA_NESS              32786
#define ID_REPROGRAMA_LLENADORAS        32787
#define ID_CAMBIAR_FECHA_INICIO         32789
#define ID_TIPO_LETRA                   32791
#define ID_SACAR_ASCII                  32792
#define ID_VERIF_STRUCT                 32793
#define ID_ORDEN_RECALCULAR             32796
#define ID_OPCIONES                     32797
#define ID_CONS_MAQORD                  32798
#define ID_CONS_CAMMOL                  32799
#define ID_CONS_LOTES                   32800
#define ID_OF_ORDEN                     32801
#define ID_SELEC_FECHA                  32802
#define ID_NEXT_PAGE                    32804
#define ID_PREV_PAGE                    32805
#define ID_NEXT_ART                     32806
#define ID_PREV_ART                     32807
#define ID_NEXT_SECCION                 32808
#define ID_PREV_SECCION                 32809
#define ID_SOLONOPROG                   32810
#define ID_OF_HASTAFECHA                32811
#define ID_CAMBIAR_FECHA_FIN            32812
#define ID_ORDENAR_MAQUINAS             32813
#define ID_OFSAYERHOY                   32814
#define ID_CONS_OFS                     32815
#define ID_DESCONTAR_OTROS              32816
#define ID_DESCONTAR_CIKA               32818
#define ID_RELOAD_DB                    32819
#define ID_VER_ACUMFECHA                32822
#define ID_EXEC_DB                      32823
#define ID_EXEC_MEZCLAS                 32824
#define ID_EXEC_SEGUNDO                 32825
#define ID_BUTTON32826                  32826
#define ID_MOLDES_EX                    32827
#define ID_EXEC_MOLDES                  32828
#define ID_BUTTON32829                  32829
#define ID_ESCALA_ESTRECHA              32830
#define ID_ESCALA_AMPLIA                32831
#define ID_CONS_MEZEXT                  32832
#define ID_CONS_MEZ_EXT                 32833
#define ID_LISTADO_SATURACIONES         32835
#define ID_CLI_ORDEN                    32836
#define ID_SOLONOFAB                    32837
#define ID_TIPO_LETRA_ST                32838
#define ID_ARCHIVO_GUARDARCONPEDIDOS    32839
#define ID_ARCHIVO_ABRIRCONPEDIDOS      32840
#define IDS_INI_CODERR                  58000
#define IDS_FIN_CODERR                  58100
#define IDS_CONF_BORRORD                61446
#define IDS_CONF_CAPTION                61447
#define IDS_ERROR                       61448
#define IDS_ERR_MOVGFH                  61449
#define IDS_WAR_MAQNOP                  61450
#define IDS_WARNING                     61451
#define IDS_GFHNOP                      61452
#define IDS_ERR_MOVNUM                  61453
#define IDS_DLG_PERSON                  61454
#define IDS_DLG_PERDES                  61455
#define IDS_ERR_PERMAX                  61456
#define IDS_ERR_NOACT                   61457
#define IDS_ERR_NOID                    61458
#define IDS_ERR_NOART                   61459
#define IDS_ERR_NOGFHART                61460
#define IDS_ERR_NOMAQ                   61461
#define IDS_ERR_NOMAQNOM                61462
#define IDS_ERR_NORECSEL                61463
#define IDS_ERR_NOMODOF                 61464
#define IDS_ERR_NOMODCAL                61465
#define IDS_ERR_NODB                    61466
#define IDS_ERR_NOOPENFILE              61467
#define IDS_ERR_NOMAQPROG               61468
#define IDS_CONF_SUBSOF                 61469
#define IDS_CONF_ADVINI                 61470
#define IDS_DEF_EXT                     61471
#define IDS_DEF_OPENDLG                 61472
#define IDS_ERR_NOREC                   61473
#define IDS_ERR_NOORDSEL                61474
#define IDS_ERR_ORDNOTF                 61475
#define IDS_ERR_OFNOOM                  61476
#define IDS_CONF_MAQNOVAC               61477
#define IDS_WAR_NOINS                   61478
#define IDS_WAR_INSJUN                  61479
#define IDS_ERR_NOMOV                   61480
#define IDS_ERR_NOMOVULT                61481
#define IDS_ERR_PROGNOVAC               61482
#define IDS_ERR_CANTMENOR               61483
#define IDS_ERR_FECFABMAY               61484
#define IDS_ERR_NOMAQID                 61485
#define IDS_ERR_NOOMENPM                61486
#define IDS_ERR_CANTNOVAL               61487
#define IDS_ERR_NOMAQAB                 61488
#define IDS_WAR_NOINSOM                 61489
#define IDS_ERR_NOMAQGFH                61490
#define IDS_ERR_OFINC                   61491
#define IDS_ERR_NOOMINC                 61492
#define IDS_DLG_CANTTIT                 61493
#define IDS_DLG_CANTTXT                 61494
#define IDS_ERR_MOLNOTFOUND             61495
#define IDS_ERR_ARTNOEX                 61496
#define IDS_CONF_ACTLIMIT               61497
#define IDS_CONF_DESC                   61498
#define IDS_DEF_EXT_PED                 61499
#define IDS_ERR_ARTNOMEZCLA             61500
#define IDS_ERR_ARTNOMOLDE              61501
#define IDS_ERR_MOLNOEXISTE             61502
#define IDS_ERR_MOLNOMAQ                61503
#define IDS_ERR_MOLMAQNOEXISTE          61504
#define IDS_ERR_MOLDENOART              61505
#define IDS_ERR_OFNOART                 61506
#define IDS_DEF_OPENDLG_PED             61507
#define IDS_WAR_NOCAD                   61508

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         32841
#define _APS_NEXT_CONTROL_VALUE         1133
#define _APS_NEXT_SYMED_VALUE           143
#endif
#endif
